on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "File created successfully"

    test:
      needs: build
      runs-on: ubuntu-latest

      steps:
        - run: echo "Test job"